name: Setup FFmpeg for Flask App

on:
  push:
    branches:
      - main  # Trigger on push to main branch, you can change this

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use 'windows-latest' or 'macos-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or any version you prefer

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your Python dependencies

      - name: Run Flask App
        run: |
          python app.py  # This will start your Flask app, but in most cases you'll run a test or build script
